//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S1.L03C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S1.L03C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not valid, minimum value is {1}..
        /// </summary>
        internal static string ArgumentOutOfRange_Error {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating salaries.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue - Esc closes the program.
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter salary {0}: .
        /// </summary>
        internal static string Enter_Salary {
            get {
                return ResourceManager.GetString("Enter_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you entered is not valid!.
        /// </summary>
        internal static string NumberOfSalaries_Error {
            get {
                return ResourceManager.GetString("NumberOfSalaries_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of salaries you wish to calculate: .
        /// </summary>
        internal static string NumberOfSalaries_Prompt {
            get {
                return ResourceManager.GetString("NumberOfSalaries_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:.
        /// </summary>
        internal static string Receipt_Average {
            get {
                return ResourceManager.GetString("Receipt_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion:.
        /// </summary>
        internal static string Receipt_Dispersion {
            get {
                return ResourceManager.GetString("Receipt_Dispersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median:.
        /// </summary>
        internal static string Receipt_Median {
            get {
                return ResourceManager.GetString("Receipt_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid input.
        /// </summary>
        internal static string Unknown_Error {
            get {
                return ResourceManager.GetString("Unknown_Error", resourceCulture);
            }
        }
    }
}
